export const CartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    CLEAR_ITEM_FROM_CART : 'CLEAR_ITEM_FROM_CART',
    ADD_CART_ITEM : 'ADD_CART_ITEM',
    REMOVE_CART_ITEM : 'REMOVE_CART_ITEM'
}